# Generated by Django 4.2 on 2023-05-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=100)),
                ('option1', models.CharField(max_length=2)),
                ('option2', models.CharField(max_length=2)),
                ('enquiry', models.TextField(max_length=300)),
                ('date', models.DateField()),
            ],
        ),
    ]
