# Generated by Django 4.2 on 2023-05-17 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=100)),
                ('place', models.TextField()),
                ('address', models.TextField()),
                ('enquiry', models.TextField()),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
