# Generated by Django 4.2 on 2023-05-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='option2',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default='N/A', max_length=250),
        ),
        migrations.AddField(
            model_name='contact',
            name='place',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
