# Generated by Django 4.1.4 on 2023-05-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='passward',
        ),
    ]
